SCREEN_WIDTH, SCREEN_HEIGHT = 320, 480
FOOD_STD_WIDTH, FOOD_STD_HEIGHT = 16, 16
FOOD_NUM = 6
INFO_BOARD_HEIGHT = 40
STD_FONT_SIZE = 25
STD_FRAME_RATE = 60

MAX_ROUNDS = 5
NUM_OF_BGS = 4
KILLER_WHALE_IMG = "img/orca.png"
SCUBA_DIVER_IMG = "img/mergulhador.png"
NARWAL_IMG = "img/narwal.png"
PLAYER_IMG = "img/player.png"
KRILL_IMG = "img/krill.png"
START_SCREEN_IMG = "img/start_alpha.png"
GAMEOVER_SCREEN_IMG = "img/game_over.png"
START_BUTTON_IMG = "img/comecar_button.png"
EXIT_BUTTON_IMG = "img/sair_button.png"
BACK_BUTTON_IMG = "img/back_button.png"
